apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: sk8s
    component: ui
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
    targetPort: 3000
  selector:
    component: ui
