apiVersion: extensions.sk8s.io/v1
kind: Topic
metadata:
  name: counts
---

apiVersion: extensions.sk8s.io/v1
kind: Function
metadata:
  name: redis-writer
spec:
  image: sk8s/redis-writer:1.0.0
  protocol: http
  input: counts
  env:
  - name: FUNCTION_URI
    value: file:///functions/function.jar?functions.RedisWriter
